platform :ios, '6.0'
pod 'pop'
pod 'AFNetworking'
pod 'SDWebImage', '~> 3.7.1'
pod 'TMCache', '~> 1.2.3'
pod 'FMDB', '~> 2.4'
pod 'shareSDK'
pod 'FXBlurView', '~> 1.6.3'
pod 'IQKeyboardManager', '~> 3.2.0.3'
pod 'MJRefresh'
pod 'MJExtension'
